// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxwvxxcwzemnjlyjqpho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4d3Z4eGN3emVtbmpseWpxcGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjAzMjgsImV4cCI6MjA2NzA5NjMyOH0.WBuBdxUQZz7_gaCpiInhx9fzsRXt6rwdHPrjYkVOme4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});